tsukumon/kbc-chat

chatapp/app/controllers/home_controller.rb
chatapp/app/helpers/home_helper.rb
chatapp/app/views/home/index.html.erb
chatapp/config/routes.rb
chatapp/spec/helpers/home_helper_spec.rb
chatapp/spec/requests/home_spec.rb

home_create

---

chatapp/app/assets/stylesheets/home.css
chatapp/app/views/layouts/application.html.erb

これはHTMLファイルとCSSファイルを同期したブランチです。
確認お願いします。

Design main

---

chatapp/app/assets/stylesheets/home.css

home.css make changes

---

chatapp/app/assets/stylesheets/application.css
chatapp/app/assets/stylesheets/home.css
chatapp/app/channels/message_channel.rb
chatapp/app/controllers/message_controller.rb
chatapp/app/javascript/application.js
chatapp/app/javascript/channels/consumer.js
chatapp/app/javascript/channels/index.js
chatapp/app/javascript/channels/message_channel.js
chatapp/app/views/room/page.html.erb
chatapp/config/importmap.rb
chatapp/config/routes.rb
chatapp/db/seeds.rb
chatapp/spec/channels/message_channel_spec.rb

real-time-chat function

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/page.html.erb
chatapp/config/routes.rb

message-delete

---

chatapp/app/models/message.rb
chatapp/app/models/room.rb

ルーム削除時にルームに紐付いたメッセージも削除するようにモデルを編集

add model assoc

---

chatapp/app/views/room/page.html.erb

organize code

---

chatapp/app/controllers/home_controller.rb
chatapp/app/controllers/room_controller.rb

メッセージ表示を降順になるように、
ルーム一覧をルーム名で昇順になるようにしました

Sort msgroom

---

chatapp/app/assets/stylesheets/room.css
chatapp/app/views/room/index.html.erb

新規作成したroomが横並びから改行されるようになりました。

Desgin index

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/page.html.erb

メッセージに改行があった場合、表示時に改行されるようにしました。
それに伴い、悪意のあるコードがメッセージに含まれていた場合、エスケープ処理されるようにしました

indention sentence& escape evil codes

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/page.html.erb

日付表示が現在の時刻も入れた条件分岐であったため、昨日のメッセージでも今日のものとして表示される場合があったため修正。
加えて、昨日のメッセージを "昨日??:??" と表示する機能も実装しました

edit for display date

---

chatapp/app/views/home/index.html.erb
chatapp/app/views/room/new_room.html.erb

ルーム詳細情報入力欄を text_area に
同時に改行がされたときに表示でも改行されるようにしました

Indention room describe

---

chatapp/app/controllers/room_controller.rb
chatapp/app/models/room.rb
chatapp/app/views/room/new_room.html.erb
chatapp/config/locales/model.ja.yml
chatapp/db/migrate/20220607005724_add_category_to_room.rb
chatapp/db/schema.rb

Roomテーブルにcategoryカラムを追加、カラムにバリデーションと別名を設定。
フォームに選択を追加

Room category

---

chatapp/app/assets/stylesheets/application.scss
chatapp/app/assets/stylesheets/room.scss
chatapp/app/javascript/channels/message_channel.js
chatapp/app/javascript/controllers/index.js
chatapp/app/views/room/page.html.erb

チャットエリア詳細変更

---

chatapp/app/views/room/edit_room.html.erb
chatapp/app/views/room/page.html.erb

ルームページ内の編集ボタン周りの編集
編集ページのViewの編集

change room page & edit page

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/index.html.erb
chatapp/app/views/room/search.html.erb

ルームのソート機能を実装しました
参加中のルーム　のページでのデフォルト表示は作成日の降順で表示されるように変更しました

Sort rooms

---

chatapp/app/views/room/index.html.erb

hide triangle

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/views/room/page.html.erb

ボタンopaつけたお

---

chatapp/app/views/room/index.html.erb

検索欄が空白でも検索できてしまっていた問題を解決。
Ransackの機能で自動でアラートも出ます

resolve blank field

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/views/room/page.html.erb

未読メッセージスクロール

---

chatapp/app/controllers/room_controller.rb
chatapp/app/models/message.rb
chatapp/app/models/room.rb
chatapp/app/models/user.rb
chatapp/app/models/user_room.rb
chatapp/app/views/layouts/application.html.erb
chatapp/app/views/room/joined.html.erb
chatapp/app/views/room/page.html.erb
chatapp/config/routes.rb
chatapp/db/migrate/20220620024405_create_user_rooms.rb
chatapp/db/schema.rb
chatapp/spec/factories/user_rooms.rb
chatapp/spec/models/user_room_spec.rb

とりあえずのルーム参加機能を実装しました
N+1解消はまだです

Room join leave

---

chatapp/app/models/message.rb
chatapp/app/models/room.rb
chatapp/app/models/user.rb
chatapp/app/models/user_room.rb
chatapp/db/migrate/20220620024405_create_user_rooms.rb
chatapp/db/schema.rb
chatapp/spec/factories/user_rooms.rb
chatapp/spec/models/user_room_spec.rb

model change

---

chatapp/app/controllers/room_controller.rb

authenticate room

---

chatapp/app/assets/stylesheets/application.scss
chatapp/app/assets/stylesheets/room.scss
chatapp/app/channels/application_cable/connection.rb
chatapp/app/channels/status_channel.rb
chatapp/app/controllers/room_controller.rb
chatapp/app/controllers/sessions_controller.rb
chatapp/app/helpers/application_helper.rb
chatapp/app/javascript/channels/index.js
chatapp/app/javascript/channels/status_channel.js
chatapp/app/views/layouts/application.html.erb
chatapp/app/views/room/page.html.erb
chatapp/db/migrate/20220629084034_add_status_to_user.rb
chatapp/db/schema.rb
chatapp/spec/channels/status_channel_spec.rb

ユーザーのオンライン・オフラインのリアルタイム表示機能を実装しました
常に表示されている自分のステータス
チャットページの最下部での仮表示を実装してあります（ルーム参加者のステータス表示）

user-status function

---

chatapp/Gemfile
chatapp/Gemfile.lock
chatapp/app/assets/stylesheets/room.scss
chatapp/app/controllers/room_controller.rb
chatapp/app/javascript/channels/message_channel.js
chatapp/app/views/room/_messages.html.erb
chatapp/app/views/room/page.html.erb

Reverse scroll

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/javascript/controllers/index.js
chatapp/app/views/room/page.html.erb

バージョン3つくらいpullしてないよ

---

chatapp/app/assets/stylesheets/application.scss
chatapp/app/assets/stylesheets/room.scss

indent naositao

---

chatapp/app/assets/stylesheets/room.scss

edit spiner

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/assets/stylesheets/rouge.scss.erb

edit style

---

chatapp/app/assets/stylesheets/application.scss
chatapp/app/assets/stylesheets/room.scss
chatapp/app/javascript/controllers/application.js

modal ittan yattao

---

chatapp/Gemfile
chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/index.html.erb
chatapp/app/views/room/joined.html.erb
chatapp/app/views/room/search_form.html.erb
chatapp/app/views/room/search_joined.html.erb
chatapp/app/views/room/search_result.html.erb
chatapp/config/routes.rb

ransackの命名規則を変更しました。（@qから@seachに変更とか）

qからsearchに変更

---

chatapp/app/controllers/room_controller.rb
chatapp/app/helpers/room_helper.rb
chatapp/app/views/room/_messages.html.erb
chatapp/app/views/room/index.html.erb
chatapp/app/views/room/joined.html.erb
chatapp/app/views/room/search.html.erb
chatapp/app/views/room/search_form.html.erb
chatapp/app/views/room/search_joined.html.erb

date_format

---

chatapp/app/javascript/controllers/application.js

fix create room modal

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/joined.html.erb

ルーム一覧を最新順に並び替え

---

chatapp/app/views/room/page.html.erb

enterで送信
shift + enter で改行
ができるようにしたお

Click submit

---

chatapp/app/controllers/room_controller.rb

ルーム作成のバリデーションのエラーのエラーの解消

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/_messages.html.erb
chatapp/app/views/room/joined.html.erb
chatapp/app/views/room/page.html.erb
chatapp/app/views/room/search_form.html.erb

Index room n+1

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/views/layouts/application.html.erb
chatapp/app/views/room/_messages.html.erb
chatapp/app/views/room/page.html.erb

とんでもないスクロールを直しました
ルーム内表示時にフェードインを追加しました

scroll-fix

---

chatapp/app/javascript/controllers/application.js

clear cache

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/index.html.erb

ルーム一覧ページで起きていたとんでもないN+1を直しました
Ransackでのソート機能は一旦消してます

fix room list N+1

---

chatapp/app/controllers/room_controller.rb

change redirect

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/_messages.html.erb
chatapp/app/views/room/_room_info.html.erb

fix room page

---

chatapp/app/controllers/room_controller.rb

参加中のルームのページで最新メッセージ順に並ぶようにしました

sort joined rooms by latest message

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/search_form.html.erb
chatapp/app/views/room/search_result.html.erb

カテゴリー検索機能削除

---

chatapp/app/views/room/joined.html.erb

参加しているルームがないとき、「参加中のルームはありません」と表示するように変更

if no joined rooms display message

---

chatapp/app/views/category/index.html.erb
chatapp/app/views/room/index.html.erb

カテゴリ別表示の部分を変更。
上のタイトルの横にソートしたカテゴリを表示するように変更
参加ボタンの横にあったカテゴリ分類ボタンの位置を変更

change category sort

---

chatapp/app/controllers/application_controller.rb
chatapp/db/migrate/20220830023345_add_admin_to_room.rb
chatapp/db/schema.rb

ルーム制作者のカラム追加

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/views/room/_messages.html.erb

class messege-one のクラス内にimgで画像の最大値を追加。

markdownで出力する画像の最大値の指定

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/_room_info.html.erb

ルーム作成者のみルーム情報を編集

---

chatapp/app/controllers/application_controller.rb

fix set_current_user

---

chatapp/app/models/room.rb

validates_admin

---

chatapp/db/migrate/20220902022701_add_private_to_room.rb
chatapp/db/schema.rb

add-column-private

---

chatapp/app/views/room/page.html.erb

Fix msg submit

---

chatapp/app/views/room/_room_info.html.erb

change room info member list

---

chatapp/app/views/home/index.html.erb
chatapp/app/views/settings/index.html.erb

ユーザー情報を設定に移行

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/_new_room.html.erb

ルーム作成フォームにメンバーを制限するチェックボックスを追加

add check roomtype for create room form

---

chatapp/app/views/room/joined.html.erb

利用者が参加しているルームに飛ぶためのリンクの範囲をtitle と image から親要素の joined-room に変更しました。

joined link

---

chatapp/app/assets/stylesheets/application.scss
chatapp/app/assets/stylesheets/room.scss
chatapp/app/controllers/category_controller.rb
chatapp/app/controllers/home_controller.rb
chatapp/app/controllers/room_controller.rb
chatapp/app/javascript/channels/message_channel.js
chatapp/app/javascript/controllers/application.js
chatapp/app/javascript/controllers/index.js
chatapp/app/views/category/index.html.erb
chatapp/app/views/home/index.html.erb
chatapp/app/views/layouts/application.html.erb
chatapp/app/views/room/_messages.html.erb
chatapp/app/views/room/_new_room.html.erb
chatapp/app/views/room/index.html.erb
chatapp/app/views/room/page.html.erb
chatapp/app/views/room/search_form.html.erb
chatapp/app/views/room/search_result.html.erb

javascirpt refactoring & bug fixed
changes:
1. all of infinite scroll
2. behavior when receipt of new message notification  
3. change focus color of message form
4. condition for event ignition  
5. fixed modal
6. fixed style, indent  
7. other detailed refact

refactoring of all javascript code in room page

---

chatapp/app/assets/stylesheets/application.scss
chatapp/app/views/room/_new_room.html.erb

Modal design

---

chatapp/app/views/room/index.html.erb

change hotroom title

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/index.html.erb

Add roomlist infscroll

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/_room_info.html.erb

もう１つ変数を作ってUser.findbyで idをroomのadminで探しに行って表示
下のfor文ではforのなかでifを作ってadmin以外を表示

管理者上固定　方法１

---

chatapp/app/javascript/controllers/index.js

メッセージ送信フォームで改行時にフォームがまれに広がらない問題を修正

fix indention flexTextarea on message form

---

chatapp/app/assets/stylesheets/room.scss

ルーム詳細情報のアコーディオンメニューのうんこを削除
矢印に変更

destroy poop

---

chatapp/app/views/room/_messages.html.erb

clean p tag

---

chatapp/app/assets/stylesheets/rouge.scss.erb

fix code block width size

---

chatapp/config/locales/ja.yml

add JP error on Carrier Wave

---

chatapp/app/javascript/channels/message_channel.js
chatapp/app/views/room/page.html.erb

メッセージの連打送信の修正
Enterで送信時には空SQLは投げられないがボタンで連打すると連打送信は阻止できるが空SQLが投げられてしまう

Msg submit fix

---

chatapp/app/assets/stylesheets/application.scss
chatapp/app/views/room/_new_room.html.erb

Fix createroom modal

---

chatapp/app/assets/stylesheets/room.scss

margin change

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/controllers/room_controller.rb
chatapp/app/javascript/channels/message_channel.js
chatapp/app/views/room/page.html.erb

ルーム内での「〇〇が参加しました」通知を実装
フェードインフェードアウトをJSで実現
もちろん他のルームの参加しましたは出ないように、「〇〇（自分自身）が参加しました」も表示されないように

add joiner notification in each chatrooms

---

chatapp/app/javascript/channels/message_channel.js

join notice display name change

---

chatapp/app/views/layouts/application.html.erb
chatapp/app/views/room/index.html.erb
chatapp/app/views/room/page.html.erb

ルーム内の戻るボタンをJS化
ルーム一覧無限スクロールの変数の初期化の修正
メニューリンクで遷移時にTurboを無効化

Change Room back button

---

chatapp/app/views/layouts/application.html.erb
chatapp/app/views/room/index.html.erb
chatapp/app/views/room/page.html.erb

Revert "Change Room back button"

---

chatapp/app/assets/stylesheets/room.scss

Revert "add join-notice-margin"

---

chatapp/app/javascript/channels/message_channel.js

Revert "join notice display name change"

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/views/room/_messages.html.erb

Revert "remake text-image desgin"

---

chatapp/app/views/layouts/application.html.erb
chatapp/app/views/room/index.html.erb
chatapp/app/views/room/page.html.erb

Revert "Revert "Change Room back button""

---

chatapp/app/javascript/channels/message_channel.js

Revert "Revert "join notice display name change""

---

chatapp/app/assets/stylesheets/room.scss
chatapp/app/views/room/_messages.html.erb

Revert "Revert "remake text-image desgin""

---

chatapp/app/controllers/room_controller.rb
chatapp/app/views/room/index.html.erb

アクティブなルームの一覧表示で単に新しいルームも表示されてしまっていたのを修正

change display active rooms

---

chatapp/app/views/room/index.html.erb

fix room list
